### ISSUE TITLE
Fächer, Noten und Zeugnisse in XSchule

### ISSUE THREAD

**Issue by FPfotenhauer** [OZG-TFBildung/XSchule#10]
**Autor:** Frank Pfotenhauer
**Art der Organisation:** Ministerium für Schule und Bildung  
**Bundesland:** NRW

**Kategorie(n) der Rückmeldung:** Fächer und Noten
**Betroffenes Feld:** Leistungsdaten

**Beschreibung:**  
Es ist ja geplant, einen XSchule-XML für die Signierung in Zeugnissen zu erstellen.
Dieses würde dann ja als XML in ein Zeugnis-PDF eingebettet.
In einem solchen Fall (wenn erlaubt) müsste dieser XML-Teil ja nicht noch einmal doppelt im Datensatz vorhanden sein.
Liege ich da richtig?

**Comment by init-xschule** [comment]
Guten Tag Herr @FPfotenhauer,

In der gerade veröffentlichten Version XSchule 0.3 werden die XML-Beispieldateien von Zeugnissen wie folgt signiert:

https://xschule.digital/def/xschule/0.3/xml/XSchule_Abiturzeugnis_NW_01.xml
https://xschule.digital/def/xschule/0.3/xml/XSchule_Abiturzeugnis_RP_01.xml
https://xschule.digital/def/xschule/0.3/xml/XSchule_Realschulzeugnis_BE_01.xml
