### ISSUE TITLE
Verwendung der Codeliste für die Art der HZB

### ISSUE THREAD

**Issue by sergejkromm** [OZG-TFBildung/XSchule#12]
**Autor:** Sergej Kromm 
**Art der Organisation:** Hersteller CaMS
**Bundesland:** NI

**Kategorie(n) der Rückmeldung:** Fachlich inhaltliche Prüfung der Abiturzeugnisse aus Sicht einer Hochschule
**Betroffenes Feld:** <xsc:artDerHZB>Allgemeine Hochschulreife</xsc:artDerHZB>

**Beschreibung:**  
Für die Übermittlung an die amtliche Statistik ist die genaue Angabe der HZB-Art erforderlich. Außerdem werden die HZB-Arten in der Geschäftslogik im Zulassungsprozess ausgewertet. Aktuell findet man im Feld xsc:artDerHZB lediglich einen String-Wert. - Unser Vorschlag: Stattdessen sollte der Schlüssel der Statistik urn:xbildung-de:xbildung:codeliste:artderhzb verwendet werden.

**Comment by sergejkromm** [comment]
Das Issue bezieht sich aus die v0.3

**Comment by sergejkromm** [comment]
Das Issue bezieht sich auf v0.3

**Comment by init-xschule** [comment]
Guten Tag,

die Verwendung des Schlüssel der Statistik im Rahmen des Zulassungsprozesses ist ein Argument, das für die (wieder-)einführung dieser Liste spräche. 

Ich habe ein entsprechendes Ticket bei XBildung erstellt.

Viele Grüße
Ludger Rinsche
