### ISSUE TITLE
Landkreis des HZB-Erwerbs

### ISSUE THREAD

**Issue by sergejkromm** [OZG-TFBildung/XSchule#13]
**Autor:** Sergej Kromm 
**Art der Organisation:** Hersteller CaMS
**Bundesland:** NI

**Kategorie(n) der Rückmeldung:** Fachlich inhaltliche Prüfung der Abiturzeugnisse aus Sicht einer Hochschule
**Betroffenes Feld:** xbd:VerwaltungspolitischeKodierung bei Bildungseinrichtungen

**Beschreibung:**
Der Landkreis des HZB-Erwerbs ist für die amtliche Studierenden-Statistik erforderlich. Der Kreis ließe sich aus xbd:VerwaltungspolitischeKodierung herauslesen. Dafür müsste in der Anschrift einer Bildungseinrichtung die Angabe zum xbd:VerwaltungspolitischeKodierung verpflichtend sein.

**Comment by sergejkromm** [comment]
Das Issue bezieht sich auf v0.3

**Comment by init-xschule** [comment]
Am 10.10.2022 wurde im Change Advisory Board von XSchule entschieden den Anwendungsfall "Statistik" weiter herunterzupriorisieren.

In V0.3 sind diese Angaben weiterhin optional möglich, wir erwägen hier aber eine Schärfung von Pflicht- und optionalen Feldern über Schematron-Regeln.

Gegen eine Verpflichtung zum Aufbringen des Landkreises in XML-Abiturzeugnissen sprechen folgende Argumente:
a) angehende Aufbau eines Statistikregister im BMBF
b) Schärfung der XSchule Anwendungsfälle auf den Bereich Leistungsverwaltung
c) Die Dynamik, die im Bereich Landkreise existiert vor dem Hintergrund von Aufbewahrungs- und Archivierungsfristen von Zeugnissen (20-50 Jahre) 

Diese Daten können aber aus der Anschrift der Schule in Verbindung mit dem Datum der Ausstellung von Dritt-Systemen ermittelt werden, wie etwa aus einer Liste aller Schulen, GDI-DE Zusammenstellungen von Bildungseinrichtungen oder der landeseigenen Auflistung von Schulen

**Comment by ArnWassmann** [comment]
Hallo in die Runde.

Aus dem Feldversuch 2.0 die Rückmeldung:
* Die Meldung des LK des Erwerbs ist eine bundesweite Aufgabe der Hochschulen
* Eine Automatisierung der Prozesse rundum die HZB ist ohne LK nicht möglich, da weiterhin nach erfasst und manuell gegen ein Zeugnis geprüft werden muss
* Die Daten liegen in der Schulsoftware vor und wären völlig unproblematisch exportierbar (bezogen auf NRW)

Daher fordern wir die Aufnahme des Landkreises des Erwerbs der HSZ in den XSchule-Standard.

Vielen Dank und beste Grüße
Arn Waßmann (HIS eG)

**Comment by init-xschule** [comment]
Guten Tag,

im dieses Anliegen auch öffentlich noch einmal zu beantworten:

Die Anschrift der Schule im Abiturzeugnis beinhaltet die Klasse `xbd:verwaltungspolitischeKodierung`:
![grafik](https://github.com/OZG-TFBildung/XSchule/assets/99478456/eef5986a-0740-446f-8633-20025a271caf)
http://xbildung.de/def/xbildung/0.95/spec/xbd_spezifikation_0.95.pdf#XBildung.Baukasten.VerwaltungspolitischeKodierung

Damit ist die Anforderung erfüllt. Für unser Beispielzeugnis kann das dann so aussehen:

```XML
        <xbd:anschrift>
            <xbd:strasse>Rampendal</xbd:strasse>
            <xbd:hausnummer>63</xbd:hausnummer>
            <xbd:postleitzahl>32657</xbd:postleitzahl>
            <xbd:ort>Lemgo</xbd:ort>
            <xbd:verwaltungspolitischeKodierung>
                <xbd:kreis listVersionID="2021-07-31">
                    <code>05766</code> <!-- Kreis Lippe -->
                </xbd:kreis>
            </xbd:verwaltungspolitischeKodierung>
        </xbd:anschrift>
```


[`http://xbildung.de/def/xbildung/0.95/spec/xbd_spezifikation_0.95.pdf#XBildung.Baukasten.Codes.Code.Kreis`](http://xbildung.de/def/xbildung/0.95/spec/xbd_spezifikation_0.95.pdf#XBildung.Baukasten.Codes.Code.Kreis)
[`https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:kreis`](https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:kreis)

Sollte das nicht Ihren Anwendungsfall abdecken, öffnen Sie bitte das Ticket erneut.
Ob die Angabe verpflichtend erfolgen kann, werden wir in der kommenden fachlichen Umfrage abfragen.
