### ISSUE TITLE
Datum des HZB-Erwerbs

### ISSUE THREAD

**Issue by sergejkromm** [OZG-TFBildung/XSchule#14]
**Autor:** Sergej Kromm 
**Art der Organisation:** Hersteller CaMS
**Bundesland:** NI

**Kategorie(n) der Rückmeldung:** Fachlich inhaltliche Prüfung der Abiturzeugnisse aus Sicht einer Hochschule
**Betroffenes Feld:**
<xbd:ausstellung>
        <xbd:datum>2021-03-21</xbd:datum>
        <xbd:ort>Mainz</xbd:ort>
</xbd:ausstellung>

**Beschreibung:**
Das Datum des HZB-Erwerbs ist für die Berechnung der Wartezeit im Zulassungsverfahren erforderlich.
Entspricht das Datum der Dokument-Ausstellung bei Abiturzeugnissen stets dem Datum des HZB-Erwerbs? Oder wird ein separates Feld für die nachgeforderten Zeugnisse bzw. im Falle einer wiederholten Zeugnisausstellung benötigt?

**Comment by sergejkromm** [comment]
Das Issue bezieht sich auf v0.3

**Comment by init-xschule** [comment]
Guten Tag,

vielen Dank für dieses Feedback. Der Bedarf ist nachvollziehbar. Wir planen eine Erweiterung von `xbd:Dokument`, um die Unterscheidung des Erwerbs und der Neuausstellung darstellen zu können.

Viele Grüße
Ludger Rinsche
