### ISSUE TITLE
Rückmeldung aus Bremen zu XSchule 0.3

### ISSUE THREAD

**Issue by nilsmiemietz** [OZG-TFBildung/XSchule#15]
**Autor:** [Nils Miemietz]  
**Art der Organisation:** [ Landesministerium Senatorin für Kinder und Bildung, wir entwickeln SVS selbst ]  
**Bundesland:** [Bremen]

**Kategorie(n) der Rückmeldung:** [Rückmeldung zur neuen Spezifikation X-Schule 0.3]
**Betroffenes Feld:** []

**Beschreibung:**  
[Bremer Rückmeldung zur Spezifikation XSchule 0.3]  

Wir haben uns die Veränderungen auf Seite 96 der PDF-Datei sowie im Issue #5 angeschaut und sind bezüglich der erledigten Veränderungen zufrieden. Es wäre gut, wenn die Veränderungen im PDF Verlinkungen zu GItHub oder zu den vorigen Seiten hätten, damit man besser nachvollziehen kann, was warum geändert wurde.

**Comment by init-xschule** [comment]
Guten Tag,

vielen Dank für dieses Feedback. 
Wir werden mit zunehmender Reife der Spezifikation die Änderungshistorie detaillierter vornehmen.

Viele Grüße
Ludger Rinsche
