### ISSUE TITLE
NI Kursart: Ergänzung der Codeliste, Trennung in 2 Listen

### ISSUE THREAD

**Issue by bwhn21** [OZG-TFBildung/XSchule#16]
**Autor:** Boris Heithecker
**Bundesland:** Niedersachsen 
**Name der Organisation:** Landesinitiative n-21

**Kategorie(n) der Rückmeldung:** Fehlende Einträge, Inhalt nicht eindeutig
**Betroffene Codeliste:** Kursart  
**Betroffene Codelisten-Version:** 0.3
**Betroffener Codelisten-Wert:** alle

**Beschreibung:**  
Diese Codeliste beschreibt aktuell zwei inhaltlich verschiedene Attribute eines Kurses/Unterrichts, nämlich den "Bereich" (Pflichtunterricht, Wahlunterricht, Wahlpflichtunterricht) und das Kursniveau in der Oberstufe. Es wird dringend vorgeschlagen, diese Liste in zwei Listen mit getrennten Bedeutungen aufzuteilen: Die Liste "Kursbereich" sollte den Bereich enthalten, dem der Unterricht in der Stundentafel und im Zeugnisformular zuzuordnen ist (Pflichtunterricht, Wahlpflichtunterricht). Die zweite Liste "Differenzierung" sollte die Niveaustufen in der Oberstufe enthalten.

Die Liste Differenzierung sollte zudem durch die Differenzierungen in der integrierten Gesamtschule und Oberschule ergänzt werden (E-Kurs, G-Kurs, Z-Kurs). 

Die Differenzierungen in der gym. Oberstufe heißen "erhöhtes Anforderungsniveau" und "grundlegendes Anforderungsniveau". 

Hinweise:
Erlass Zeugnisse in den allgemeinbildenden Schulen http://www.schure.de/22410/36-3-83203.htm , siehe Muster in der Anlage
Die Arbeit in den Schuljahrgängen 5 bis 10 des Gymnasiums http://www.schure.de/22410/33-81011.htm , siehe Stundentafeln in der Anlage
Die Arbeit in der HS http://www.schure.de/22410/32-81023-1-hs.htm , Abschnitt 3.1
Die Arbeit in der RS http://www.schure.de/22410/32-81023-1-rs.htm, Abschnitt 3.1
Die Arbeit in der IGS http://www.schure.de/22410/32-2-81071.htm , Abschnitt 3.1 und 6.3.1.1 Für die Fachleistungsdifferenzierung in E-Kurs und G-Kurs
Die Arbeit in der KGS http://www.schure.de/22410/34-81072.htm , Abschnitt 3.1
Die Arbeit in der Oberschule http://www.schure.de/22410/32-81028.htm, Abschnitt 3.1 sowie 6.4.1 zur Fachleistungsdifferenzierung in E-Kurs, G-Kurs und Z-Kurs

<!--
Es wird davon ausgegangen, dass das Issue sich auf die aktuelle Version von XSchule bezieht. Sollte dies nicht der Fall sein, erwähnen Sie es bitte in der Beschreibung.
Weitere Punkte, die in der Beschreibung besonders hilfreich sind, sind zum Beispiel:  
 - Herleitung des Änderungsbedarfs aus der Verwaltungspraxis (wofür wird eine Änderung benötigt)
 - Beschreibung des Anwendungsfalls  
 - Häufigkeit des Vorkommens  
 - Bezug zu anderen Spezifikationen  

Bedeutung der Kategorien "Mapping (bei Import/Export) unklar":
  Werden XSchule-Daten in Ihr System importiert, kann es sein, dasss ein XSchule-Wert zu mehreren internen Werten passt.
  Werden Daten aus Ihrem System exportiert, kann es sein, dass zum internen Wert mehrere XSchule-Werte passen.

**Comment by bwhn21** [comment]
Es bezieht sich auf V0.3, der Label stimmt nicht.

**Comment by init-xschule** [comment]
Sehr geehrter Herr Heithecker, @bwhn21 
Vielen Dank.

Wir sehen nun die Trennung der aktuellen Codeliste Kursart in zwei Listen für die V0.4 vor:

In unserem internen Ticketsystem wurden angelegt:
XSC-196 Codeliste Kursdifferenzierung erstellen und 
XSC-197  Codeliste Kursbereich erstellen.

Das Ticket XSC-196 beschreibt folgende Codewerte und Beschreibungen.

Sind die Beschreibungen aus Ihrer Sicht so korrekt?

Herausgeber: XSchule

URN: urn:xschule-digital:xschule:codeliste:kursdifferenzierung

Werte:

Codename	_Beschreibung_
 [http://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/grundlegendes_anforderungsniveau](https://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/grundlegendes_anforderungsniveau) 	_grundlegendes Anforderungsniveau (früher: Grundkurs), verwendet u.a. für Kurse der gymnasialen Oberstufe_
[http://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/erweitertes_anforderungsniveau](https://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/grundlegendes_anforderungsniveau) 	_erweitertes Anforderungsniveau (früher Leistungskurs), verwendet u.a. für Kurse der gymnasialen Oberstufe_
[http://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/e-kurs](https://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/grundlegendes_anforderungsniveau)	_E-Kurs, (Erweiterter Kurs) verwendet u.a. für Kurse der integrierten Gesamtschule und Oberschule_ 
[http://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/g-kurs](https://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/grundlegendes_anforderungsniveau)	_G-Kurs, (Grundkurs) verwendet u.a. für Kurse der integrierten Gesamtschule und Oberschule_ 
[http://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/z-kurs](https://xschule.digital/def/xschule/0.4/code/kursdifferenzierung/grundlegendes_anforderungsniveau)	_Z-Kurs, (Zusatzkurs) verwendet u.a. für Kurse der integrierten Gesamtschule und Oberschule_

**Allgemeiner Implementierungshinweis an Hersteller zu XSchule-Codelisten:** URL, Herausgeber und einzelne Code-Werte können sich mit zunehmender länderübergreifender Abstimmung noch ändern. 
Außerdem werden wir ab einer fortgeschritteneren XSchule-Version davon absehen, die Versionskennung (hier 0.4) in unveränderten Codelisten hochzuzählen und nichtversionierte URIs anbieten. Es ist geplant RDF-Dateien hinter den URIs auszuliefern, welche nach Möglichkeit die [W3C Best Practice Recipes](https://www.w3.org/TR/swbp-vocab-pub/) for publishing RDF-Vocabularies (hier: slash-URIs) berücksichtigen, wie etwa hier in XHochschule für die DESTATIS Hochschulsignatur der Universität Hannover zu sehen: https://xhochschule.de/def/destatis/WS21/code/hochschulsignatur/1450

**Comment by bwhn21** [comment]
Ja, passt gut.

**Comment by init-xschule** [comment]
In der V0.4 wurden nun folgende Codelisten veröffentlicht:

Kursbereich:
https://github.com/OZG-TFBildung/XSchule/blob/main/code/urn-xschule-digital-xschule-codeliste-kursbereich.xml


Kursdifferenzierung:
https://github.com/OZG-TFBildung/XSchule/blob/main/code/urn-xschule-digital-xschule-codeliste-kursdifferenzierung.xml

**Comment by FPfotenhauer** [comment]
Wie kann man denn aus der CodeListe erkennen, dass das nur für Niedersachsen gilt?

**Comment by init-xschule** [comment]
Guten Tag Herr Pfotenhauer,

in beiden Codelisten verwenden wir (auch) Begriffe, die von der KMK vorgegeben werden. Sind auch diese nicht anwendbar, bleibt festzuhalten, dass die Codelisten nie in einem verpflichtenden Kontext verwendet werden.

Das Problem, das Sie ansprechen, ist damit aber natürlich nicht abschließend gelöst. Wir befinden uns in einem Spannungsfeld zwischen Vereinheitlichung, Landesspezifikas und dem Nutzen von Codelisten. Im Jahresendworkshop wurde klar artikuliert, dass Codelisten gegenüber Freitextfeldern zu bevorzugen sind. Im kommenden Jahr werden wir einen Vorschlag erarbeiten, wie sich die Vorteile von Codelisten mit einer bundeslandspezifischen Profilierung des Standards vereinigen lassen und dies in einem Release entsprechend umsetzen.

Frohe Feiertage!
