### ISSUE TITLE
ArtDesSchulabschlusses-Codes: kurze Nachfrage und Hinweis zu evtl ergänzendem Wert

### ISSUE THREAD

**Issue by sroertgen** [OZG-TFBildung/XSchule#18]
**Autor:** Steffen Rörtgen
**Bundesland:** Niedersachsen
**Name der Organisation:** Kompetenzzentrum Interoperable Metadaten [Curricula-Gruppe](https://wiki.dnb.de/display/DINIAGKIM/Curricula-Gruppe)

**Kategorie(n) der Rückmeldung:** Nachfrage zu Code-Liste: Art des Schulabschlusses
**Betroffene Codeliste:** ArtDesSchulabschlusses-Codes
**Betroffene Codelisten-Version:** 0.92
**Betroffener Codelisten-Wert:** alle

**Beschreibung:**  

Hallo zusammen,

in der [Curricula-Gruppe](https://wiki.dnb.de/display/DINIAGKIM/Curricula-Gruppe) beschäftigen wir uns ebenfalls gerade mit der Abbildung von Schulabschlüssen und veröffentlichen dieses als SKOS: 
- [Schulabschluesse](https://skohub.io/dini-ag-kim/schulabschluesse/heads/main/w3id.org/kim/schulabschluesse/index.de.html)  (Hinweis die W3-Weiterleitung muss noch geschaltet werden)
- [Git-Repo](https://github.com/dini-ag-kim/schulabschluesse) 

In unserer Gruppe kam dabei folgende Frage auf: In der aktuellen Spec wird die Code-Liste nicht verlinkt. Wird diese Code-Liste nicht verwendet werden oder ist die Implementierung in einer späteren Spec geplant?

Außerdem noch ein Hinweis aus den Diskussionen in unserer Gruppe: In einem von der KMK veröffentlichten Dokument [Grundstruktur des Bildungswesens in der Bundesrepublik Deutschland](https://www.kmk.org/fileadmin/Dateien/pdf/Dokumentation/de_2019.pdf) wird noch die "fachgebundene Hochschulreife" erwähnt. Dieser Abschluss wird zumindest in einigen Bundesländern ermöglicht (Hinweis in unserer Gruppe kam aus Rheinland-Pfalz) und berechtigt, anders als die Fachhochschulreife, zum Studium an einer Universität, jedoch nur zum Studium ausgewählter Fächer.

Viele Grüße
Steffen

**Comment by init-xschule** [comment]
Guten Tag,

derzeit veröffentlichen wir unsere eigene Codeliste, basierend auf der [Fachserie 11, Reihe 1, 2009/10](https://www.statistischebibliothek.de/mir/receive/DEHeft_mods_00005582). 
Zum Beispiel: https://xbildung.de/def/xbildung/0.93/code/ArtDesSchulabschlusses/allgemeine_hochschulreife

Ein Wechsel der Codeliste zu der von Ihnen erstellten Liste bzw. die Aufnahme in einer kommenden Version von XBildung, wird zu diskutieren sein.

Ich habe ein dazugehöriges Issue bei XBildung erstellt.

Vielen Dank für diese Anregung
Ludger Rinsche
