### ISSUE TITLE
Beispiel einer XML-Struktur zur Spezifikation hinzufügen

### ISSUE THREAD

**Issue by markschies-fhh-bsb** [OZG-TFBildung/XSchule#2]
Autor: Kay Markschies

Art der Organisation: Freie und Hansestadt Hamburg, Behörde für Schule und Berufsbildung, Referat IT-Fachverfahren und Projekte

Beschreibung: Generell wäre es gut, wenn der Spezifikation eine XML-Beispieldatei hinzugefügt werden würde ("Max Mustermann"). Dies würde aus meiner Sicht das Verständnis zur Einhaltung der XML Schema Definition zusätzlich fördern und Strukturänderungen für Entwickler schneller begreifbar machen.

**Comment by markschies-fhh-bsb** [comment]
zurückgezogen, da nach genauerer Betrachtung genau diese Bespiele wohl im XML-Verzeichnis zu finden sind.

**Comment by markschies-fhh-bsb** [comment]
Dann öffne ich doch noch einmal dieses Issue, denn in Spezifikation 0.1.1 ist das XML-Verzeichnis mit den Beispieldateien leider verschwunden.

**Comment by init-xschule** [comment]
Vielen Dank für Ihren Hinweis @markschies-fhh-bsb, den wir soweit vom XÖV-Produktionszubehör möglich gern berücksichtigen. 
Aktuell ist eine Versionierung im Dateinamen nur noch bei 
a) der Spezifikation selbst
b) bei Genericode-Dateien für die Wertelisten im Dateinamen gegeben.

In den XSD-Dateien, den Schematron-Regeln, den Magic Draw und XMI-Modellen sowie in den Instanzdateien lässt sich zukünftig dank gleichbleibenden Dateinamen die DIFF-Funktionalität gut nutzen. 

Wir prüfen für das kommende Release (auch bei den verwandten Vorhaben XBildung und XHochschule), ob sich der Punkt b) auch noch verbessern lässt. Außerdem stellen wir in XSchule zusätzlich eine Änderungshistorie ab der Version 0.3 im Anhang der Spezifikation zur Verfügung.
