### ISSUE TITLE
Angabe der Spezifikationsnummer in den Dateien möglichst vermeiden

### ISSUE THREAD

**Issue by markschies-fhh-bsb** [OZG-TFBildung/XSchule#3]
Autor: Kay Markschies
Art der Organisation: Freie und Hansestadt Hamburg, Behörde für Schule und Berufsbildung

Beschreibung: Beim Release der Spezifikation 0.1.1 haben sich relativ viele Neuerungen in der Art ergeben, dass veränderte Spezifikationen (z.B. zum Bildungsgang) in eine neue Datei verbracht worden sind, die jeweils die Versionsnummer im neuen Dateinamen tragen.

Dies führt bei der Betrachtung der einzelnen Commits dazu, dass immer eine Datei gelöscht und eine neue erstellt worden ist. Dadurch geht der Vorteil von Diffs verloren, die ja genau die Sourcecodeänderung innerhalb einer Datei deutlich machen sollen.

Meine Empfehlung wäre, Versionsinformationen zukünftig nicht mehr in Dateinamen einfließen zu lassen.

**Comment by markschies-fhh-bsb** [comment]
Wenn es von Version zu Version zu grundlegenden Veränderungen kommt, wäre es naheliegender, für diesen Versionswechsel der Spezifikation einen neuen Branch anzulegen und diesen nach der Versionsnummer zu betiteln.

**Comment by init-xschule** [comment]
Vielen Dank für Ihren Hinweis @markschies-fhh-bsb, den wir soweit vom XÖV-Produktionszubehör möglich gern berücksichtigen. 
Aktuell ist eine Versionierung im Dateinamen nur noch bei 
a) der Spezifikation selbst
b) bei Genericode-Dateien für die Wertelisten im Dateinamen gegeben.

In den XSD-Dateien, den Schematron-Regeln, den Magic Draw und XMI-Modellen sowie in den Instanzdateien lässt sich zukünftig dank gleichbleibenden Dateinamen die DIFF-Funktionalität gut nutzen. 

Wir prüfen für das kommende Release (auch bei den verwandten Vorhaben XBildung und XHochschule), ob sich der Punkt b) auch noch verbessern lässt. Außerdem stellen wir in XSchule zusätzlich eine Änderungshistorie ab der Version 0.3 im Anhang der Spezifikation zur Verfügung.

**Comment by init-xschule** [comment]
Guten Tag Herr @markschies-fhh-bsb ,

wir haben basierend auf ihrem Vorschlag die Benennung der Dateien angepasst.
