### ISSUE TITLE
Berücksichtigung der Punkteskala für Gesamtpunktzahl

### ISSUE THREAD

**Issue by sfhschneider** [OZG-TFBildung/XSchule#4]
Autor: Steve Schneider
Art der Organisation: SfH 
Beschreibung: 
In der Spezifikation ist unter II.1.2. Qualifikation die **Gesamtpunktzahl** und die **Durchschnittsnote** vorgesehen. Es fehlt allerdings in diesem Kontext noch die Angabe der maximal erreichbaren Punktzahl, die zwingend notwendig ist. Als Ausprägungen sind mindestens die Werte "900", "840" und "sonstige" sowie "keine Angabe" erforderlich.

**Comment by init-xschule** [comment]
Vielen Dank @sfhschneider für Ihre Anmerkung, die wir gern im nächsten Release berücksichtigen. 

Wir würden uns bei der Umsetzung dabei an den zukünftigen SDG-Modell Klasse "Grade" für den Bildungsbereich orientieren und auch zusätzlich zum von Ihnen vorgeschlagenen "maximum grade" ein "passing grade" optional ermöglichen.  Was meinen Sie als SfH dazu?


![image](https://user-images.githubusercontent.com/99478456/155286162-9db2ae10-2267-4ede-9512-c5f7c0ef03e3.png)
Quelle:
https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_tables.md

**Comment by sfhschneider** [comment]
Vielen Dank für die Rückmeldung. Aus Sicht der SfH spricht Nichts gegen die zusätzliche optionale Aufnahme des "passing grade".  Da diese Angabe auch auf den gedruckten Zeugnisexemplaren vorhanden ist, würde sich damit eine Deckungsgleichheit zwischen gedruckten Zeugnissen und der digitalen Variante realisieren lassen. 
Das Feld "maximum grade" muss obligatorisch vorhanden sein.

**Comment by init-xschule** [comment]
In XBildung V0.92 
[https://xbildung.de/def/xbildung/0.92/spec/spezifikation_0.92.pdf#page=43](https://xbildung.de/def/xbildung/0.92/spec/spezifikation_0.92.pdf#page=43)
wurde dies nun mit deutschen Begriffen so gelöst:
`besteBewertung` (entspricht maximum grade)
`schlechtesteBewertung` (entspricht minimum grade)
`bestandenAbBewertung` (entspricht passing grade)


![image](https://user-images.githubusercontent.com/99478456/181490233-494fe2f4-264e-4949-9ead-6446d7a47c21.png)

zusätzlich zur generischen Angabe wurde für die häufig verwendeten Bewertungsschemata der Leistungen aus dem Abiturblock I, II und III in XBildung V0.92 
feste URIs als Codelistenwerte erstellt.
[https://xbildung.de/def/xbildung/0.92/spec/spezifikation_0.92.pdf#page=74](https://xbildung.de/def/xbildung/0.92/spec/spezifikation_0.92.pdf#page=74)

Damit kann im Kontext einer Note oder einem Punkt jeweils das anzuwendende Bewertungsschema mitgeteilt werden:

![image](https://user-images.githubusercontent.com/99478456/181490996-149cc3dc-db4b-40b2-8386-83ecf2ea5c37.png)


Die konkrete Verwendung auf Ebene von Instanzdateien ist ([ab August](https://xschule.digital/web/releaseplanung)) im XSchule Abiturzeugnis V0.3 zu sehen:
