### ISSUE TITLE
Rückmeldung aus Bremen zu XSchule 0.2

### ISSUE THREAD

**Issue by nilsmiemietz** [OZG-TFBildung/XSchule#5]
Autor: [Nils Miemietz]
Art der Organisation: [ Ministerium - wir entwickeln im Ministerium selbst unsere SVS ]
Beschreibung: [erbetene Rückmeldung gemäß E-Mail vom 10.03.2022 von XSchule]

Wir haben die Spezifikation XSchule_0.2 geprüft und haben aus Bremen folgende Anmerkungen:

zu II.1.3 Schulkurs: Uns fehlen zwei Felder:
Eingebracht ja/nein: Ist der Kurs ein für die Abiturnote relevanter Kurs und fließt in die Berechnung ein - ja oder nein.
Schwerpunkt: Im Fach Sport oder ggf. auch anderen Fächern kann es noch Schwerpunkte geben. 
Berechnungsgrundlage und Bewertungsschema verstehen wir nicht 

zu II.1.4  Zeugnis: Halbjahreszeugnis heißt bei uns Zwischenzeugnis § 8 Abs.2 Zeugnisverordnung
Die weiteren Zeugnisnamen finden sich in den §§ 9ff. Zeugnisverordnung: [https://www.transparenz.bremen.de/metainformationen/verordnung-fuer-zeugnisse-und-lernentwicklungsberichte-an-oeffentlichen-schulen-zeugnisverordnung-vom-20-juni-2013-90707?asl=bremen203_tpgesetz.c.55340.de&template=20_gp_ifg_meta_detail_d#jlr-ZeugnVBR2013V4P10b](url)

zu II.1.5 Art der HZB: Hier ist nicht ganz klar, wo schulischer Teil der FHR einzustufen ist, wenn ein Lernender die GyO vorzeitig verlässt, den schulischen Teil der FHR aber schon erreicht hat.

zu II.1.7 Prüfungsergebnis: Da fehlt uns die Kursart LK oder GK sowie Reihenfolge der Prüfungsergebnisse. Die Prüfungsergebnisse werden in Bremen sortiert nach 1. Lk, 2.Lk, 3.PF, 4.PF auf dem Zeugnis ausgegeben. 

zu II.1.8  Schueler: Das Geburtsland fehlt für statistische Auswertungen

zu II.1.10 Schule In der Codetabelle Bildungsgang bitte g8/g9 ergänzen, denn in Bremen gibt es Schulen, bei denen beides möglich ist.

zu II.1.14 Einschulung: Der Begriff Einschulung ist ungünstig / Aufnahme Grundschule wäre besser --> Es gibt Geflüchtete, die nicht in die 1. Klasse aufgenommen werden, sondern zunächst in Alphabetisierungsklassen alphabetisiert werden, da sie in ihrem Herkunftsland nie in eine Schule gegangen sind. Später wechseln sie dann in eine alters- und Bildungsstand gerechte Klasse. Für diese Kinder ist es dann eine Einschulung. Für alle anderen Kinder wäre "Aufnahme Grundschule" der bessere Begriff für den Standard.

zu II.1.16 Daten zum gesetzlichen Vertreter: Gesetzlicher Vertreter Sterbetag und Tag der Beerdigung Ist dies aus Datenschutzgründen überhaupt erlaubt? Wir in Bremen haben diese Daten nicht. Auch das Geburtsdatum des gesetzlichen Vertreters kennen wir in Bremen nicht. Hier unsere Meldedatenübertragungsverordnung:  

Geburtsdatum gesetzlicher Vertreter  ZeugnVBR2013V4P10b](url)

zu II.1.5 Art der HZB: Hier ist nicht ganz klar, wo schulischer Teil der FHR einzustufen ist, wenn ein Lernender die GyO vorzeitig verlässt, den schulischen Teil der FHR aber schon erreicht hat.

zu II.1.7 Prüfungsergebnis: Da fehlt uns die Kursart LK oder GK sowie Reihenfolge der Prüfungsergebnisse. Die Prüfungsergebnisse werden in Bremen sortiert nach 1. Lk, 2.Lk, 3.PF, 4.PF auf dem Zeugnis ausgegeben. 

zu II.1.8  Schueler: Das Geburtsland fehlt für statistische Auswertungen

zu II.1.10 Schule In der Codetabelle Bildungsgang bitte g8/g9 ergänzen, denn in Bremen gibt es Schulen, bei denen beides möglich ist.

zu II.1.14 Einschulung: Der Begriff Einschulung ist ungünstig / Aufnahme Grundschule wäre besser --> Es gibt Geflüchtete, die nicht in die 1. Klasse aufgenommen werden, sondern zunächst in Alphabetisierungsklassen alphabetisiert werden, da sie in ihrem Herkunftsland nie in eine Schule gegangen sind. Später wechseln sie dann in eine alters- und Bildungsstand gerechte Klasse. Für diese Kinder ist es dann eine Einschulung. Für alle anderen Kinder wäre "Aufnahme Grundschule" der bessere Begriff für den Standard.

zu II.1.16 Daten zum gesetzlichen Vertreter: Gesetzlicher Vertreter Sterbetag und Tag der Beerdigung Ist dies aus Datenschutzgründen überhaupt erlaubt? Wir in Bremen haben diese Daten nicht. Auch das Geburtsdatum des gesetzlichen Vertreters kennen wir in Bremen nicht. Hier unsere Meldedatenübertragungsverordnung:  [https://www.transparenz.bremen.de/metainformationen/verordnung-zur-uebermittlung-von-meldedaten-meldduev-vom-19-oktober-2017-157599?asl=bremen203_tpgesetz.c.55340.de&template=20_gp_ifg_meta_detail_d#jlr-MeldDUumlVBRpP10](url)

zu I.1.21: NotenübersichtundZeugnis: Was verstehen Sie unter Notenübersicht unterjähriger Wechsel? 

Grundsätzliche Hinweise aus Bremen: EBBR und BBR statt Hauptschule und wir haben Oberschulen statt Gesamtschulen

**Comment by init-xschule** [comment]
**XSC-138 Begriff "Art Der Einschulung" überprüfen**
Nach Bestätigung in der Umfrage IV haben wir die Codeliste umbenannt in `art_der_schulaufnahme`

**XBD-163 Angabe Schwerpunkt in Kurs ermöglichen**
In XBildung V0.92 
[https://xbildung.de/def/xbildung/0.92/spec/spezifikation_0.92.pdf#page=50](https://xbildung.de/def/xbildung/0.92/spec/spezifikation_0.92.pdf#page=50)
wurde nun der Schwerpunkt als mehrsprachige Zeichenkette in den Kurs, und damit in den Schulkurs bei XSchule eingebracht.

![image](https://user-images.githubusercontent.com/99478456/181508254-6a24edc3-c66f-483f-8b71-e211a4ad8104.png)

**XBD-6 Codeliste "Art der Hochschulzugangsberechtigung" in XBildung anpassen:**
Die `ArtderHZB` wurde in XSchule V0.3 von der Codeliste zu einer Zeichenkette zurückgebaut. 
Kodifiziert kann der DQR=4 für Abiturzeugnisse mit xbd:niveau angegeben werden.
![image](https://user-images.githubusercontent.com/99478456/181508908-525068d2-43c9-4a4b-9291-9fca0ace6788.png)

**XSC-136 Inhalte in Instanzdatei Zeugnis erweitern - Geburtstaat**
Deutschland wurde im Wechseldatensatz ergänzt
![image](https://user-images.githubusercontent.com/99478456/181512483-2d706c14-c966-4103-9c81-e92f75f9d90c.png)


**XSC-134 Codeliste Bildungsgang Wert g8/g9 ergänzen:** 
Der Bildungsgang G8/G9 wurde ergänzt

**Comment by init-xschule** [comment]
Guten Tag Herr @nilsmiemietz ,

Die Codeliste ` Bewertungsschema ` sieht wie folgt aus:
 
![image](https://user-images.githubusercontent.com/99478456/183655157-8976677d-4e6a-49ee-ac5b-f10c92f64607.png)


In die Liste `ArtDesZeugnisses ` wurden folgende Werte aufgenommen:
	 
![image](https://user-images.githubusercontent.com/99478456/183655178-7847e55d-5c2b-412e-93d2-1badfa07bc8d.png)


Die Code-Liste `Kursart` beinhaltet folgende Werte:
 
![image](https://user-images.githubusercontent.com/99478456/183655224-22dca8ba-16de-4aad-86c5-a8d3f6f7fc0b.png)

<img width="632" alt="image" src="https://user-images.githubusercontent.com/99478456/183672597-5a7b9491-d84b-41a9-a336-1e4e8b7692b1.png">


Die Angaben zum Sterbetag und Tag der Beerdigung bei dem gesetzlichen Vertreter sind optional. 
 
![image](https://user-images.githubusercontent.com/99478456/183655254-a17e7c05-501a-46ed-8d8f-5a510c309a45.png)
