### ISSUE TITLE
CodeListe Gesetzliche Vertreter

### ISSUE THREAD

**Issue by FPfotenhauer** [OZG-TFBildung/XSchule#6]
Autor: Frank Pfotenhauer
Art der Organisation: MSB NRW 
Beschreibung: Nachfrage zu Codelisten und Speicherung der Erzieher

Wir versuchen gerade SchülerOnline <> XSchule <> SVWS (Schulverwaltungssoftware) NRW mit den Datenfeldenr zu mappen.
Danach würde wir einmal versuchen einen Schülerdatensatz von SVWS zu übergeben und einen Datensatz von SO zu übernehmen.

Woher bekommen wir die Schlüssel zu den gesetzlichen Vertretern Spezifikation Seite 28?

Wir speichern verschiedene Datensätze zu Sorgeberechtigten.
Bei Eltern gibt es zwei Personen in einem Datensatz.
Man kann aber auch 2 (und mehr) Datensätze zu einem Schülerdatensatz speichern.

Wie ist das in XSchule vorgesehen?

**Comment by init-xschule** [comment]
Vielen Dank @FPfotenhauer für Ihre Anfrage.

Diese externe Codeliste nach DSMeld Blatt 0001, deren Werte sich theoretisch außerhalb des XSchule-Releasezyklus ändern könnten sind nicht in der Spezifikation abgedruckt sondern im XRepository (www.xrepository.de) hinterlegt.

Sie können dort durch Eingabe der in XSchule gelisteten "URN" in der Suchmaske des XRepositories auf diese Codeliste oder gelangen oder direkt durch diesen Link:
https://www.xrepository.de/details/urn:de:dsmeld:schluesseltabelle:gesetzlicher.vertreter

In XSchule sind keine, einer oder mehrere (0..*) Datensätze zu einem natürlichen oder nicht natürlichen "gesetzlichenVertreter" im Rahmen der Daten eines Schulwechsel von der abgebenden an eine aufnehmende Schule vorgesehen.
