### ISSUE TITLE
Kontaktmöglichkeiten

### ISSUE THREAD

**Issue by FPfotenhauer** [OZG-TFBildung/XSchule#7]
Autor: Frank Pfotenhauer
Art der Organisation: MSB NRW
Beschreibung: Wie sollen Kontaktmöglichkeiten geführt werden

In XSchule werden Kontaktmöglichkeiten bei den jeweilien Personen (Gesetzllicher Vertreter) geführt.
Wir haben in der Schulverwaltungssoftware Zu den Schüler*innen mehrere Telefonnummern und Email-Adressen.
Diese Telefonnummern gehören dann u.U. zu Erzieher und können freie Bezeichnungen haben. (Z.B Mobil, Arbeit, Notfall)

Wie soll das in XSchule abgebildet werden?

**Comment by init-xschule** [comment]
Vielen Dank Herr @FPfotenhauer für Ihre Frage.

Wir nutzen die in XÖV definierte Kernkomponente "Kommunikation" nach.
Dort haben Sie neben `Kanal` und `Kennung `noch die folgenden zwei Möglichkeiten `Zusatz` und `istDienstlich` den Kommunikationskanal näher zu präzisieren:
https://xbildung.de/def/xbildung/0.9/spec/spezifikation_0.9.pdf  Seite 44:
![image](https://user-images.githubusercontent.com/99478456/165484323-c4581cb7-7522-437d-ac31-5b2621aeb6fc.png)

Gern nehmen wir Ihr Beispiel "Notfall" in zukünftigen Beispieldateien auf.
Für den Aspekt "Arbeit" ist in der XÖV-Kernkomponente ein Flag "istDienstlich" vorgesehen.

**Comment by FPfotenhauer** [comment]
Für mich wäre die Frage damit beantwortet.

**Comment by init-xschule** [comment]
In XSchule V0.3 haben wir nun in den Instanzdateien zum Wechsel einen Notfallkontakt exemplarisch aufgenommen:

https://xschule.digital/def/xschule/0.3/xml/XSchule_Wechsel_01.xml (Erreichbar ab KW31)

![image](https://user-images.githubusercontent.com/99478456/181507942-7682eb14-b33e-437b-ad07-30294bb3327a.png)
