### ISSUE TITLE
Daten von Ausbildungsbetrieben

### ISSUE THREAD

**Issue by FPfotenhauer** [OZG-TFBildung/XSchule#8]
**Autor:** Frank Pfotenhauer
**Art der Organisation:** Ministerium für Schule und Bildung  
**Bundesland:** NRW

**Kategorie(n) der Rückmeldung:** Frage zu Daten der Betriebe
**Betroffenes Feld:** Alle Felder zu Betrieben, Standorten des Betriebs, Ansprechpartner

**Beschreibung:**  
In NRW wollen wir XSchule auch für den landesinternen Wechsel nutzen.
Schüler*inenn die vom Berufskollge kommen oder an ein BK gehen haben oft einen Betrieb.
Wir Speichern diese Betriebe mit Adressen, Kommunikation und Ansprechpartnern (z.B. Ausbilder)
https://wiki.svws.nrw.de/mediawiki/index.php?title=Schnittstellenbeschreibung#Adressen.dat
https://wiki.svws.nrw.de/mediawiki/index.php?title=Schnittstellenbeschreibung#Ansprechpartner.dat

Bei Import zum Schüler:
https://wiki.svws.nrw.de/mediawiki/index.php?title=Schnittstellenbeschreibung#SchuelerAdressen.dat

Wie ist hier die Speicherung in XSchule vorgesehen?

**Comment by init-xschule** [comment]
Guten Tag Herr @FPfotenhauer ,

in der XSchule Version 0.3 wird hat die besuchte Schule den Typ 'Organisation', der auf folgende Kinderelemente verfügt: 
<img width="235" alt="image" src="https://user-images.githubusercontent.com/99478456/183438129-9db7c967-0b11-4f12-8034-ca61a45d7423.png">
Somit ist die Angabe von der Anschrift und Kommunikation möglich.

Die Nachricht `schueler.wechsel.0001` bezieht sich derzeit auf die Anmeldung eines Schülers / einer Schülerin an einer anderen Schule. Ob diese Nachricht auch für den Use-Case des Wechsels an ein Berufskollegs geeignet ist oder dafür erweitert werden muss, können wir im Rahmen der Entwicklung der Version 0.4 diskutieren. Für diese Version wird der Schwerpunkt auf der Wechsel-Nachricht liegen.
